[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1

# Backend service
[[services]]
name = "backend"
sourcePath = "Vue Backend/Portfolio-Backend"
startCommand = "java -jar target/*.jar"

# Frontend service
[[services]]
name = "frontend" 
sourcePath = "Vue Frontend/portfolio"