spring.application.name=Portfolio-Backend
# MongoDB configuration
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=Portfolio_Database
# If authentication is required:
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=password
# spring.data.mongodb.authentication-database=admin

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#server.port=8081

# JPA properties (not needed for MongoDB)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false

# Logging
#logging.level.com.example.formdemo=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG

server.port=8081
server.servlet.context-path=/api 

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/Portfolio_Database}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:Portfolio_Database}

cors.allowed.origins = http://localhost:80,http://localhost:8080

loggin.level.com.example.Portfolio_Backend=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=DEBUG
